# Generated by Django 4.2.7 on 2024-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='text',
            new_name='course_title',
        ),
        migrations.AddField(
            model_name='resources',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resources',
            name='lecturer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resources',
            name='level',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resources',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
