# Generated by Django 4.2.7 on 2024-01-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_text_resources_course_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='department',
            new_name='programme',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
