# Generated by Django 5.0 on 2024-01-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_photo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
